name: build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17.x', '1.16.x' ]
    name: Build WasmEdge-go on Ubuntu 20.04 x86_64 with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check go version
        run: go version
      - name: Install wasmedge
        run: |
          wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all -v 0.10.1-alpha.2
      - name: Build WasmEdge-go without any extensions
        run: |
          source $HOME/.wasmedge/env
          go build ./wasmedge/
      - name: Build WasmEdge-go with tensorflow and images extensions
        run: |
          source $HOME/.wasmedge/env
          go build -tags image,tensorflow ./wasmedge/
      - name: Build WasmEdge-go with tensorflowlite and images extensions
        run: |
          source $HOME/.wasmedge/env
          go build -tags image,tensorflowlite ./wasmedge/

  build_macos:
    runs-on: macos-11
    strategy:
      matrix:
        go: [ '1.17.x', '1.16.x' ]
    name: Build WasmEdge-go on MacOS 11 x86_64 with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check go version
        run: go version
      - name: Install wasmedge
        run: |
          wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all -v 0.10.1-alpha.2
      - name: Build WasmEdge-go without any extensions
        run: |
          source $HOME/.wasmedge/env
          go build ./wasmedge/
      - name: Build WasmEdge-go with tensorflow and images extensions
        run: |
          source $HOME/.wasmedge/env
          go build -tags image,tensorflow ./wasmedge/
      - name: Build WasmEdge-go with tensorflowlite and images extensions
        run: |
          source $HOME/.wasmedge/env
          go build -tags image,tensorflowlite ./wasmedge/
